<x-community>

    <div class="page-heading header-text sustain">
        <div class="container">
            <div class="row">

            </div>

        </div>
    </div>

    <div class="section best-deal">
        <div class="container-fluid">
            <div class="row">
                <div>
                    <div class="tabs-content">
                        <div class="row">
                            <div class="col-lg-11 mx-auto">
                                <div class="section-heading">
                                    <h4>Highlights About Our Solutions</h4>
                                </div>
                                <div class="nav-wrapper ">
                                    <ul class="nav nav-tabs" role="tablist">
                                        <li class="nav-item" role="presentation">
                                            <button class="nav-link active" id="appartment-tab" data-bs-toggle="tab"
                                                data-bs-target="#appartment" type="button" role="tab"
                                                aria-controls="appartment" aria-selected="true">Environmental</button>
                                        </li>
                                        <li class="nav-item" role="presentation">
                                            <button class="nav-link" id="villa-tab" data-bs-toggle="tab"
                                                data-bs-target="#villa" type="button" role="tab"
                                                aria-controls="villa" aria-selected="false">Sustainable</button>
                                        </li>
                                        <li class="nav-item" role="presentation">
                                            <button class="nav-link" id="penthouse-tab" data-bs-toggle="tab"
                                                data-bs-target="#penthouse" type="button" role="tab"
                                                aria-controls="penthouse" aria-selected="false">Amenities</button>
                                        </li>

                                    </ul>
                                </div>
                                <div class="tab-content" id="myTabContent">
                                    <div class="tab-pane fade show active" id="appartment" role="tabpanel"
                                        aria-labelledby="appartment-tab">
                                        <div class="row">

                                            <ul>
                                                <li>
                                                    PROJECT ROADMAP TO ENERGY INDEPENDENCE
                                                </li>
                                                <li>Based on this model, by 2025, all of Belize can be fossil fuel
                                                    free. Financing for this program has been already secured in
                                                    principle.</li>
                                                <li>
                                                    By utilizing only 40% of the lagoon surface area, a floating
                                                    solar field can generate 100 Megawatts of peak power, which
                                                    is currently the peak power load for the entire country.

                                                </li>
                                                <li>
                                                    At an average peak power production of 4 hours per day, over
                                                    146GWh will be produced annually, which would fully cover
                                                    Belize’s electricity purchased from Mexico and generated by
                                                    fossil fuels during the day

                                                </li>
                                                <li>
                                                    The Majority ofthe solar power will be used to power the
                                                    BalamReserve and other island projects and stored in
                                                    batteries netting these projects at Carbon Negative.
                                                </li>
                                            </ul>

                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="villa" role="tabpanel"
                                        aria-labelledby="villa-tab">
                                        <div class="row">

                                            <ul>
                                                <li>
                                                    POWER

                                                </li>
                                                <li>
                                                    Floatingsolardistributedacross BalamReserveand other
                                                    communities/islands (estimated 20-100 megawatts)
                                                </li>
                                                <li>
                                                    WASTER

                                                </li>
                                                <li>
                                                    Conversioninto electricity. Upon completion of project
                                                </li>
                                                <li>
                                                    SEWER
                                                </li>
                                                <li>
                                                    Klargester bio-disc individual biological treatment system
                                                </li>
                                                <li>
                                                    NET ZER0 CO2 EMISSION
                                                </li>

                                                <li>
                                                    Planting 1.5Milliontreeson3,000acreson(our)
                                                    property, with the help of the Mennonites.
                                                    Nofossilfuel-driven cars.
                                                </li>
                                                <li>
                                                    TECHNOLOGY CENTER
                                                </li>
                                                <li>
                                                    Conrad Net-ZeroInstitute forSustainability
                                                </li>
                                                <li>
                                                    WATER
                                                </li>
                                                <li>
                                                    Desalination supported atmospheric water supply,
                                                    gray water recycling.

                                                </li>
                                            </ul>

                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="phase4" role="tabpanel"
                                        aria-labelledby="phase4-tab">
                                        <div class="row">

                                            <ul>
                                                <li>
                                                    • 182 acres oceanfront parcel with 550
                                                </li>
                                                <li>
                                                    • Villas 305 rooms Hotel

                                                </li>
                                                <li>
                                                    • Golf Course
                                                </li>

                                            </ul>


                                            <div class="icon-button">
                                                <a href="#"><i class="fa fa-calendar"></i> Schedule a visit</a>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="penthouse" role="tabpanel"
                                        aria-labelledby="penthouse-tab">
                                        <div class="row">

                                            <ul>
                                                <li style="list-style-type: disc">
                                                    Small Hospital
                                                </li>
                                                <li style="list-style-type: disc">
                                                    Tele Medicine

                                                </li>
                                                <li style="list-style-type: disc">

                                                    Professional Healing
                                                </li>
                                                <li style="list-style-type: disc">

                                                    Nondenominational Church
                                                </li>
                                                <li style="list-style-type: disc">
                                                    Security Building

                                                </li>
                                                <li style="list-style-type: disc">
                                                    Art Park

                                                </li>
                                                <li style="list-style-type: disc">
                                                    The Conrad Net-Zero

                                                </li>
                                                <li style="list-style-type: disc">

                                                    Institute Marina
                                                </li>
                                                <li style="list-style-type: disc">

                                                    Airport
                                                </li>
                                                <li style="list-style-type: disc">

                                                    Golf Course
                                                </li>
                                                <li style="list-style-type: disc">

                                                    High speed WiFi
                                                </li>
                                                <li style="list-style-type: disc">
                                                    Organic Farming

                                                </li>
                                            </ul>
                                          

                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid pt-4">
            <div class="row">
                <div class="col-lg-4">
                    <div class="section-heading">

                        <h4>CREATING BEYOND</h4>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="tabs-content">
                        <div class="row">
                            <div class="nav-wrapper">
                                <ul class="nav nav-tabs" role="tablist">
                                    <li class="nav-item" role="presentation">
                                        <button class="nav-link active" id="appartment-tab" data-bs-toggle="tab"
                                            data-bs-target="#appartment" type="button" role="tab"
                                            aria-controls="appartment" aria-selected="true">
                                            RISKS
                                        </button>
                                    </li>

                                </ul>
                            </div>
                            <div class="tab-content" id="myTabContent">
                                <div class="tab-pane fade show active" id="appartment" role="tabpanel"
                                    aria-labelledby="appartment-tab">
                                    <div class="row">
                                        {{-- <div class="col-lg-9"> --}}
                                        <img class="col-lg-8" src="{{ asset('assets/images/image13.png') }}"
                                            alt="">
                                        {{-- </div> --}}

                                        <div class="col-lg-4">
                                            <h4>SPECIFIC RISKS RELATED TO THE PROJECT</h4>
                                            <p>
                                                Market:
                                                As a Real estate and tourism increases in Belize, there couble be
                                                increased competition.
                                            </p>
                                            <p>
                                                Environmental: Area Prone to negative impact of hurricanes and risk of
                                                flooding could lead to property damage
                                            </p>
                                            <p>
                                                Financial:
                                                Development completion could take significantly longer and be more
                                                expensive then budgeted.
                                            </p>
                                            <p>
                                                Other:
                                                As a International development, currency movement and political
                                                stability must be taken in consideration.
                                            </p>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>







</x-community>
